mi_est_app/urls.py
from django.urls import path
from . import views

app_name = 'mi_est_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('estacionamientos/', views.estacionamientos, name='estacionamientos'),
    path('estacionamiento/<int:id>',
         views.estacionamiento, name='estacionamiento'),
    path('nuevo_estacionamiento/', views.nuevo_arriendo,
         name='nuevo_estacionamiento'),
    path('editar_arriendo/<int:id>',
         views.editar_arriendo, name='editar_arriendo'),
    path('eliminar_arriendo/<int:id>',
         views.elimiar_arriendo, name='eliminar_arriendo'),
    path('ver_estacionamiento/<int:id>',
         views.ver_estacionamiento, name='ver_estacionamiento'),
    path('estacionamiento_arrendado/<int:id>',
         views.estacionamiento_arrendado, name='estacionamiento_arrendado'),
    path('arriendos/', views.arriendos, name='arriendos'),
    path('arriendo/<int:id>', views.arriendo, name='arriendo'),
]

mi_est_cuentas/urls.py
from django.urls import path, include
from . import views

app_name = 'mi_est_cuentas'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('registro/', views.registro, name='registro'),
]

mi_est_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mi_est_app.urls')),
    path('mi_est_cuentas/', include('mi_est_cuentas.urls'))
]

mi_est_app/models.py
from django.db import models
from django.contrib.auth.models import User


class EnArriendo(models.Model):
    titulo = models.CharField(max_length=128)
    precio = models.CharField(max_length=100)
    fecha = models.DateTimeField(auto_now_add=True)
    tipo = models.CharField(max_length=128)
    desc = models.TextField()
    ancho = models.CharField(max_length=100)
    largo = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo


class EstArrendado(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    source_model = models.ForeignKey(
        EnArriendo, null=False, blank=False, on_delete=models.CASCADE)

mi_est_cuentas/models.py
from django.db import models

# Create your models here.

mi_est_app/forms.py
from django import forms
from .models import EnArriendo


class ArreindoForm(forms.ModelForm):
    class Meta:
        model = EnArriendo
        fields = ['titulo', 'precio', 'tipo', 'largo', 'ancho', 'desc']

mi_est_cuentas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistroUsuario(UserCreationForm):
    username = forms.CharField(
        max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=100, widget=forms.EmailInput(
        attrs={'class': 'form-control'}))
    password1 = forms.CharField(
        label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(
        label="Confirme Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email ya se encuentra registrado')
        return email

mi_est_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import EnArriendo, EstArrendado
from .forms import ArreindoForm

# Create your views here.


def index(request):
    estacionamientos = EnArriendo.objects.all()
    return render(request, 'mi_est_app/index.html', {'estacionamientos': estacionamientos})


@login_required
def dashboard(request):
    return render(request, 'mi_est_app/dashboard.html')


@login_required
def estacionamientos(request):
    esta = EnArriendo.objects.filter(owner=request.user)
    context = {'esta': esta}
    return render(request, 'mi_est_app/estacionamientos.html', context)


@login_required
def estacionamiento(request, id):
    esta = EnArriendo.objects.filter(owner=request.user).get(id=id)
    context = {'esta': esta}
    return render(request, 'mi_est_app/estacionamiento.html', context)


@login_required
def ver_estacionamiento(request, id):
    esta = EnArriendo.objects.get(id=id)
    context = {'esta': esta}
    return render(request, 'mi_est_app/ver_estacionamiento.html', context)


@login_required
def estacionamiento_arrendado(reqeust, id):
    en_arriendo = EnArriendo.objects.get(id=id)
    esta_arrendado, created = EstArrendado.objects.get_or_create(
        user=reqeust.user,
        source_model=en_arriendo
    )
    return redirect('mi_est_app:arriendos')


@login_required
def arriendos(request):
    arriendo = EstArrendado.objects.filter(user=request.user)
    context = {'arriendo': arriendo}
    return render(request, 'mi_est_app/arriendos.html', context)


@login_required
def arriendo(request, id):
    arriendo = EstArrendado.objects.filter(user=request.user).get(id=id)
    context = {'arriendo': arriendo}
    return render(request, 'mi_est_app/arriendo.html', context)


@login_required
def nuevo_arriendo(request):
    if request.method == 'POST':
        form = ArreindoForm(data=request.POST)
        if form.is_valid():
            est_form = form.save(commit=False)
            est_form.owner = request.user
            est_form.save()
            return redirect('mi_est_app:estacionamientos')
    else:
        form = ArreindoForm()

    context = {'form': form}
    return render(request, 'mi_est_app/nuevo_est.html', context)


@login_required
def editar_arriendo(request, id):
    esta = EnArriendo.objects.filter(owner=request.user).get(id=id)
    if request.method != 'POST':
        form = ArreindoForm(instance=esta)
    else:
        form = ArreindoForm(instance=esta, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('mi_est_app:estacionamientos')

    context = {'esta': esta, 'form': form}
    return render(request, 'mi_est_app/editar_arriendo.html', context)


@login_required
def elimiar_arriendo(request, id):
    esta = EnArriendo.objects.filter(owner=request.user).get(id=id)
    esta.delete()
    return redirect('mi_est_app:estacionamientos')

mi_est_cuentas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import RegistroUsuario


def registro(request):
    if request.method == 'POST':
        form = RegistroUsuario(request.POST)

        if form.is_valid():
            form.save()
            new_user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, new_user)
            return redirect('mi_est_app:index')
    else:
        form = RegistroUsuario()

    context = {'form': form}
    return render(request, 'registration/registro.html', context)

# Create your views here.

mi_est_app/templates/mi_est_app/arriendo.html
{% extends "mi_est_app/base.html" %}

{% block page_header %}
    <h3>Estacionamiento: {{ arriendo.source_model.titulo }}</h3>
{% endblock page_header %}

{% block content %}
    
    <ul class="list-group border-bottom pb-2 mb-4">
        <li class="list-group-item border-0">Tipo de estacionamiento: {{ arriendo.source_model.tipo }}</li>
        <li class="list-group-item border-0">Precio: {{ arriendo.source_model.precio }}</li>
        <li class="list-group-item border-0">Ancho: {{ arriendo.source_model.ancho }}</li>
        <li class="list-group-item border-0">Largo: {{ arriendo.source_model.largo }}</li>
        <li class="list-group-item border-0">Descripcion: {{ arriendo.source_model.desc }}</li>
    </ul>
{% endblock content %}

mi_est_app/templates/mi_est_app/arriendos.html
{% extends "mi_est_app/base.html" %}

{% block page_header %}
    <h3>Mis Estacionamientos Arrendados</h3>
{% endblock page_header %}  

{% block content %}
    <ul class="list-group border-bottom pb-2 mb-4">
        {% for arr in arriendo %}
            <li class="list-group-item border-0"><a href="{% url 'mi_est_app:arriendo' arr.id %}">{{ arr.source_model.titulo }}</a></li>
        {% empty %}
            <p>No tiene estacionamietnos arrendados</p>
        {% endfor %}
    </ul>
{% endblock content %}

mi_est_app/templates/mi_est_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi estacionamiento</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container-fluid">

            <a class="navbar-brand" href="{% url 'mi_est_app:index' %}">Mi Estacionamiento</a>

            <ul class="navbar-nav ms-auto mb-2 mb-md-o">
                {% if user.is_authenticated %}
                    <li class="nav_item px-4">
                        Bienvenido, {{ user.username }}
                    </li>
                    <br>
                    <li class="nav_item px-4">
                        <a href="{% url 'mi_est_app:dashboard' %}">Mi cuenta</a>
                    </li>
                {% else %}
                    <li class="nav_item px-4">
                        <a href="{% url 'mi_est_cuentas:login' %}">Ingresar</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'mi_est_cuentas:registro' %}">Registrate!</a>
                    </li>
                {% endif %}
            </ul>

            {% if user.is_authenticated %}
            <form action="{% url 'mi_est_cuentas:logout' %}">
                <button class="btn btn-outline-secondary btn-sm" name="submit">Salir</button>
            </form>
            {% endif %}
        </div>
    </nav>

    <main class="container">
        <div class="pb-2 mb-2 border-button">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
    

</body>
</html>

mi_est_app/templates/mi_est_app/dashboard.html
{% extends "mi_est_app/base.html" %}
{% load django_bootstrap5 %}


{% block content %}

    <div style='text-align: center'>
        <form action="{% url 'mi_est_app:estacionamientos' %}">
            {% bootstrap_button button_type="submit" content="Mis estacionamientos" %}
        </form>
        <br>
        <form action="{% url 'mi_est_app:arriendos' %}">
            {% bootstrap_button button_type="submit" content="Mis arriendos" %}
        </form>

    </div>

{% endblock content %}

mi_est_app/templates/mi_est_app/editar_arriendo.html
{% extends "mi_est_app/base.html" %}
{% load django_bootstrap5 %}

{% block content %}

    <h3>{{ esta.titulo }}</h3>

    <form action="{% url 'mi_est_app:editar_arriendo' esta.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Editar" %}
    </form>

{% endblock content %}

mi_est_app/templates/mi_est_app/estacionamiento.html
{% extends "mi_est_app/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Estacionamiento: {{ esta.titulo }}</h2>
{% endblock page_header %}

{% block content %}

    <div class="card-header">
        <ul class="list-group border-bottom pb-2 mb-4">
            <li class="list-group-item border-0">Publicado: {{ esta.fecha }}</li>
            <li class="list-group-item border-0">Tipo de estacionamiento: {{ esta.tipo }}</li>
            <li class="list-group-item border-0">Precio: {{ esta.precio }}</li>
            <li class="list-group-item border-0">Ancho: {{ esta.ancho }} cm</li>
            <li class="list-group-item border-0">Largo: {{ esta.largo }} cm</li>
            <li class="list-group-item border-0">Descripcion: {{ esta.desc }}</li>
        </ul>
    </div>
    
    <form action="{% url 'mi_est_app:editar_arriendo' esta.id %}">
        {% bootstrap_button button_type="submit" content="Editar arriendo" %}
    </form>
    <br>
    <form action="{% url 'mi_est_app:eliminar_arriendo' esta.id%}">
        {% bootstrap_button button_type="submit" content="Eliminar arriendo" %}
    </form>
{% endblock content %}

mi_est_app/templates/mi_est_app/estacionamientos.html
{% extends "mi_est_app/base.html" %}
{% load django_bootstrap5 %}


{% block page_header %}
    <h3>Mis estacionamientos en arriendo</h3>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'mi_est_app:nuevo_estacionamiento' %}">
        {% bootstrap_button button_type="submit" content="Agregar nuevo estacionamiento" %}
    </form>
    <br>
    <ul class="list-group border-bottom pb-2 mb-4">
        {% for est in esta %}
            <li class="list-group-item border-0"><a href="{% url 'mi_est_app:estacionamiento' est.id %}">{{ est.titulo }}</a></li>
        {% empty %}
            <li>No hay estacionamientos registrados</li>
        {% endfor %}
    </ul>
    
{% endblock content %}

mi_est_app/templates/mi_est_app/index.html
{% extends 'mi_est_app/base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h2 class="display-3">Estacionamientos disponibles</h2>
            <br>
            <div>
                {% for est in estacionamientos %}
                <ul>
                    <li><h4><a href="{% url 'mi_est_app:ver_estacionamiento' est.id %}">{{ est.titulo }}</a></h4></li>
                    <li>{{ est.precio }}</li>
                </ul>
                {% endfor %}
            </div>
        </div>

    </div>
{% else %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h2 class="display-3">Bienvenido!</h2>
            <br>
            <p class="lead">
                Bienvenido a la plataforma Mi Estacionamiento donde podras encontrar estacionamientos en arriendo para tu vehiculo
            </p>
            </div>
        </div>

    </div>
{% endif %}

{% endblock content %} 

mi_est_app/templates/mi_est_app/nuevo_est.html
{% extends "mi_est_app/base.html" %}
{% load django_bootstrap5 %}

{% block content %}

    <form action="{% url 'mi_est_app:nuevo_estacionamiento' %}" method="post">

        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Crear nuevo estacionamiento" %}

    </form>

{% endblock content %}

mi_est_app/templates/mi_est_app/ver_estacionamiento.html
{% extends "mi_est_app/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h3>{{ esta.titulo }}</h3>
{% endblock page_header %}

{% block content %}

    <ul class="list-group border-bottom pb-2 mb-4">
        <li class="list-group-item border-0">Publicado: {{ esta.fecha }}</li>
        <li class="list-group-item border-0">Tipo de estacionamiento: {{ esta.tipo }}</li>
        <li class="list-group-item border-0">Precio: {{ esta.precio }}</li>
        <li class="list-group-item border-0">Ancho: {{ esta.ancho }} cm</li>
        <li class="list-group-item border-0">Largo: {{ esta.largo }} cm</li>
        <li class="list-group-item border-0">Descripcion: {{ esta.desc }}</li>
        <br>

        <form action="{% url 'mi_est_app:estacionamiento_arrendado' esta.id%}" method="post">
            {% csrf_token %}
            {% bootstrap_button button_type="submit" content="Agregar a arriendos" %}
        </form>
    </ul>


{% endblock content %}